language: android

jdk:
    - oraclejdk8

android:
    components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-28

before_install:
    - source environmentSetup.sh && copyEnvVarsToUserProperties

script:
    - ./gradlew clean build

notifications:
    email: false

sudo: false

cache:
    directories:
        - $HOME/.gradle

deploy:
    skip_cleanup: true
    provider: script
    script: ./deploy.sh
    on:
        repo: keiththompson/hockey-tree
        all_branches: true
        tags: true
